version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: miniinstagram-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: miniinstagram
      POSTGRES_USER: miniuser
      POSTGRES_PASSWORD: minipass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
